title: Kai Stats
description: Exploring sustainability, intelligence, and the beauty of structure.
url: "https://kai-stats.github.io"
baseurl: ""
theme: jekyll-theme-minimal

# ページ上のリンク（indexで描画）
nav:
  - title: Projects
    url: /projects
  - title: Blog
    url: /blog/
  - title: GitHub
    url: https://github.com/kai-stats

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
